[package]
name = "firework"
version = "0.1.0"
authors = ["Ritoban Roy-Chowdhury <ritobanrc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
anyhow = "1.0"
ultraviolet = "0.4.5"
tiny-rng = "0.1.0"
image = "0.22.4"
